version: '3.10'
services:

  app:
    build: .
    volumes:
      - .:/provider_b
    ports:
      - 9002:9002
    image: app:provider_b
    container_name: provider_b
    command: python manage.py runserver 0.0.0.0:9002
