# Generated by Django 4.1.3 on 2022-12-03 09:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProvidersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
                ('search_id', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'verbose_name': 'Данные поиска с провайдеров',
                'verbose_name_plural': 'Данные поиска с провайдеров',
                'ordering': ['-created_at'],
            },
        ),
    ]
