# Generated by Django 4.1.3 on 2022-12-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providersdata',
            old_name='data',
            new_name='items',
        ),
    ]
