# Generated by Django 4.1.3 on 2022-12-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0002_rename_data_providersdata_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='providersdata',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='providersdata',
            name='items',
            field=models.JSONField(default=None),
        ),
    ]
